PORT = /dev/ttyUSB1
PORT_SPEED = 9600
ARDUINO_FQBN = "arduino:avr:nano"

NN_ADDR1 = 0x02
NN_ADDR2 = 0x01

CLOCK_PIN = 2
DATA_PIN = 4

ifndef DEVICE
	DEVICE = 2
	DEVICE_LOADED = 1
	include Makefile
endif
